- name: Überwache Nginx und führe Self-Healing durch
  hosts: all
  become: yes
  tasks:
      - name: Überprüfe, ob Nginx läuft
        ansible.builtin.command: systemctl is-active --quiet nginx
        register: nginx_status
        changed_when: false
        ignore_errors: yes

      - name: Starte Nginx neu, falls er gestoppt ist
        ansible.builtin.service:
            name: nginx
            state: restarted
        when: nginx_status.rc != 0

      - name: Schreibe in Logdatei, falls der Neustart fehlschlägt
        ansible.builtin.lineinfile:
            path: /var/log/nginx_monitor.log
            line: "{{ ansible_date_time.iso8601 }} - Nginx ist ausgefallen und konnte nicht neu gestartet werden!"
            create: yes
        when: nginx_status.rc != 0
