- name: Installiere Apache-Tools (htpasswd)
  apt:
      name:
          - apache2-utils
          - python3-passlib
      state: present

- name: Erstelle /etc/nginx/.htpasswd
  file:
      path: /etc/nginx/.htpasswd
      state: touch
      owner: root
      group: root
      mode: "0644"

- name: Generiere Zugangsdaten für Boss-Benutzer
  community.general.htpasswd:
      path: /etc/nginx/.htpasswd
      name: "{{ item.name }}"
      password: "{{ item.name }}123!" # Sicherer Passwortgenerator empfohlen
      state: present
  loop: "{{ users | selectattr('position', 'equalto', 'Boss') | list }}"
- name: Lösche Inhalt von /etc/nginx/sites-available/default
  ansible.builtin.copy:
      content: ""
      dest: /etc/nginx/sites-available/default
      mode: "0644"

- name: Konfiguriere Nginx für geschützte VIP-Seiten
  blockinfile:
      path: /etc/nginx/sites-available/default

      block: |
          server {
            listen 80 default_server;
            listen [::]:80 default_server;
            root /var/www/html;
            server_name _;
            location / {
                    # First attempt to serve request as file, then
                    # as directory, then fall back to displaying a 404.
                    try_files $uri $uri/ =404;
            }
            {% for user in users %}
            {% if user.position == "Boss" %}
            location /{{ user.name }}.html {
                auth_basic "Restricted Area";
                auth_basic_user_file /etc/nginx/.htpasswd;
            }
            {% else %}
            location /{{ user.name }}.html {
                allow all;
            }
            {% endif %}
            {% endfor %}
          }
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
  notify: Neustarte Nginx
